import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "John Doe - Full Stack Developer & UI/UX Designer",
  description:
    "Portfolio of John Doe, a passionate full stack developer and UI/UX designer creating beautiful, functional digital experiences.",
  keywords: "full stack developer, UI/UX designer, React, Next.js, TypeScript, portfolio",
  authors: [{ name: "John Doe" }],
  openGraph: {
    title: "John Doe - Full Stack Developer & UI/UX Designer",
    description: "Portfolio showcasing my work in web development and design",
    type: "website",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
